# Generated by Django 5.0.3 on 2024-03-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='skud_time',
            new_name='skud_datetime',
        ),
    ]
