version: "3.7"

services:
  backend:
    build: ./backend
    container_name: 'backend'
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'

  refresher:
    build: ./refresher
    container_name: 'refresher'
    restart: always
    depends_on:
      - backend
    command: python main.py

