# Generated by Django 5.0.3 on 2024-03-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CL', 'Клиент'), ('WR', 'Сотрудник')], default='CL', max_length=20)),
                ('skud_number', models.IntegerField(default=0)),
                ('skud_direction', models.CharField(choices=[('IN', 'in'), ('OUT', 'out')], default='OUT', max_length=20)),
                ('skud_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
